# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  clean: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $VstsPAT = "$env:SYSTEM_ACCESSTOKEN"
      $vstsProject = "pipeline_templates"
      $githubOrg = "bordertech"

      git branch -r | findstr /v "\->" |  ForEach-Object {$br=$_.TrimStart(); git branch --track $br.TrimStart("origin/") $br}

      $repoName = "$env:BUILD_REPOSITORY_NAME".split('/')[1]
      echo $repoName

      $vstsRepoUri = "$env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI".Substring(8) + "$vstsProject/_git/$repoName"
      echo $vstsRepoUri

      $githubRepoUri = "github.com/$githubOrg/$repoName"
      echo $githubRepoUri

      #git remote add vsts "https://$env:SYSTEM_ACCESSTOKEN@$repoUri"
      #git branch -r | findstr /v "\->" |  ForEach-Object { $br=$_.TrimStart("  origin/"); git push -u vsts $br }
  env:
    SYSTEM_ACCESSTOKEN: $(system.accesstoken)
